apiVersion: v1
kind: Service
metadata:
  name: devsecops-demo
  labels:
    app: devsecops-demo
    owner: platform-team
spec:
  selector:
    app: devsecops-demo
  ports:
    - port: 80
      targetPort: 8000